---
title: "解構式與異常"
date: 2023-05-07 13:27
tags:
- cpp
---
> 在 C++11 中，Destructor and `delete` 被自動宣告為  `noexcept`。



[[Modern C++ noexcept]]

## 情境: 當Destructor 必須執行某項會丟Exception 的程序
舉例，我們有一個資料庫連線的 class `DBConnection`，這類資源管理的 Class 在 [[Chapter3]] 中會有更詳細的探討。
```cpp
class DBConnection {
public:
...
static DBConnection create();   // function to return DBConnection objects; params omitted for simplicity
void close(); 
// close connection; throw an exception if closing fails
};  
```


### 直接 Catch Exception
為了防止 client 沒有 close connection 就直接刪除物件，我們需要在 destructor 呼叫 `close`，然而這個 function 有丟出 exception 的風險。
有兩種做法可以簡單的解決
1. 使用 `std::abort` 提前中止程式，它可以搶在 Exception 傳出去之前，也就是 Undefined Behavior 傳出去之前，強迫程式結束。
	```cpp
DBConn::~DBConn() {
	try { db.close(); }
	catch (...) {
		// make log entry that the call to close failed;
		std::abort();
	}
}
	```
2. 吞下異常。一般來說，這是個壞主意，它抑制了錯誤被知道的機會。
	```cpp
DBConn::~DBConn() {
	try { db.close(); }
	catch (...) {
		// make log entry that the call to close failed;
	}
}
	```

哪種方法好，端看情境如何取捨。不過此兩者做法都不是根本解決之道。

## 解決方法: 讓 Cilent 自己接住 Exception
更好的做法是重新設計 Interface，讓 client 端自己 `close`，對 Exception 做反應。並在 destructor 當中再設一道確保關閉的雙重保障 -- 如果客戶還是忘了關，再讓 destructor 動手吧! 


## 質疑
- 轉移責任到 Client 身上的嫌疑? 並沒有，因為 destructor 中也是有一道 Check。
- 違反[[讓介面易於被使用，不易誤用]]? 

如果某個操作有 raise exception 的風險，又必須處理該 exception，這個異常必須來自 destructor 之外的某個 function (此例: 來自 `close`)，而這有讓 client 端接手的必要性，將它轉移出 destructor 能避免 undefined behavior 的發生有更大的價值。
